### ISSUE TITLE
setPaymentMethodOnCart is incomplete

### ISSUE THREAD

**Issue by BarryBadpak** [Ingenico-ePayments/connect-extension-magento2-graphql#2]
Currently payments can not be fully set when using the GraphQL mutation `setPaymentMethodOnCart`. 

A plugin needs to be created in order to process the payment method payload that will be passed along with this request.

Reference:
`vendor/magento/module-paypal-graph-ql/Model/Plugin/Resolver/SetPaymentMethodOnCart.php`
https://devdocs.magento.com/guides/v2.3/graphql/mutations/set-payment-method.html

**Comment by kanduvisla** [comment]
This issue has been resolved in the latest `0.1.3` release
